// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

/*
Package math is a generated protocol buffer package.

It is generated from these files:
	math.proto

It has these top-level messages:
	Complex128
	Vector
	Matrix
*/
package math

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math1 "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math1.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Complex128 struct {
	Absolute float64 `protobuf:"fixed64,1,opt,name=absolute" json:"absolute,omitempty"`
	Theta    float64 `protobuf:"fixed64,2,opt,name=theta" json:"theta,omitempty"`
}

func (m *Complex128) Reset()                    { *m = Complex128{} }
func (m *Complex128) String() string            { return proto.CompactTextString(m) }
func (*Complex128) ProtoMessage()               {}
func (*Complex128) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Complex128) GetAbsolute() float64 {
	if m != nil {
		return m.Absolute
	}
	return 0
}

func (m *Complex128) GetTheta() float64 {
	if m != nil {
		return m.Theta
	}
	return 0
}

type Vector struct {
	Vector []*Complex128 `protobuf:"bytes,1,rep,name=vector" json:"vector,omitempty"`
}

func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Vector) GetVector() []*Complex128 {
	if m != nil {
		return m.Vector
	}
	return nil
}

type Matrix struct {
	Vectors []*Vector `protobuf:"bytes,1,rep,name=vectors" json:"vectors,omitempty"`
}

func (m *Matrix) Reset()                    { *m = Matrix{} }
func (m *Matrix) String() string            { return proto.CompactTextString(m) }
func (*Matrix) ProtoMessage()               {}
func (*Matrix) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Matrix) GetVectors() []*Vector {
	if m != nil {
		return m.Vectors
	}
	return nil
}

func init() {
	proto.RegisterType((*Complex128)(nil), "math.Complex128")
	proto.RegisterType((*Vector)(nil), "math.Vector")
	proto.RegisterType((*Matrix)(nil), "math.Matrix")
}

func init() { proto.RegisterFile("math.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2c, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xec, 0xb8, 0xb8, 0x9c, 0xf3,
	0x73, 0x0b, 0x72, 0x52, 0x2b, 0x0c, 0x8d, 0x2c, 0x84, 0xa4, 0xb8, 0x38, 0x12, 0x93, 0x8a, 0xf3,
	0x73, 0x4a, 0x4b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x18, 0x83, 0xe0, 0x7c, 0x21, 0x11, 0x2e,
	0xd6, 0x92, 0x8c, 0xd4, 0x92, 0x44, 0x09, 0x26, 0xb0, 0x04, 0x84, 0xa3, 0x64, 0xc4, 0xc5, 0x16,
	0x96, 0x9a, 0x5c, 0x92, 0x5f, 0x24, 0xa4, 0xc1, 0xc5, 0x56, 0x06, 0x66, 0x49, 0x30, 0x2a, 0x30,
	0x6b, 0x70, 0x1b, 0x09, 0xe8, 0x81, 0x2d, 0x43, 0x98, 0x1e, 0x04, 0x95, 0x57, 0x32, 0xe0, 0x62,
	0xf3, 0x4d, 0x2c, 0x29, 0xca, 0xac, 0x10, 0x52, 0xe3, 0x62, 0x87, 0x88, 0x15, 0x43, 0x35, 0xf1,
	0x40, 0x34, 0x41, 0x8c, 0x0c, 0x82, 0x49, 0x3a, 0x49, 0x73, 0x09, 0x26, 0xe7, 0xe7, 0xea, 0xa5,
	0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x17, 0x27, 0x66, 0x98, 0xa4, 0x56, 0x39, 0x81, 0x3d, 0x10,
	0xc0, 0x98, 0xc4, 0x06, 0xf6, 0x8f, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xea, 0xa0, 0x35, 0x52,
	0xdd, 0x00, 0x00, 0x00,
}
