// Code generated by protoc-gen-go. DO NOT EDIT.
// source: q.proto

/*
Package qsim is a generated protocol buffer package.

It is generated from these files:
	q.proto

It has these top-level messages:
	Q
	QRequest
	ApplyRequest
	ControlledRequest
	QResponse
*/
package qsim

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import qubit "qubit"
import math1 "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Q struct {
	Qubit *qubit.Qubit `protobuf:"bytes,1,opt,name=qubit" json:"qubit,omitempty"`
}

func (m *Q) Reset()                    { *m = Q{} }
func (m *Q) String() string            { return proto.CompactTextString(m) }
func (*Q) ProtoMessage()               {}
func (*Q) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Q) GetQubit() *qubit.Qubit {
	if m != nil {
		return m.Qubit
	}
	return nil
}

type QRequest struct {
	Q []*Q `protobuf:"bytes,1,rep,name=q" json:"q,omitempty"`
}

func (m *QRequest) Reset()                    { *m = QRequest{} }
func (m *QRequest) String() string            { return proto.CompactTextString(m) }
func (*QRequest) ProtoMessage()               {}
func (*QRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QRequest) GetQ() []*Q {
	if m != nil {
		return m.Q
	}
	return nil
}

type ApplyRequest struct {
	M *math1.Matrix `protobuf:"bytes,1,opt,name=m" json:"m,omitempty"`
	Q []*Q          `protobuf:"bytes,2,rep,name=q" json:"q,omitempty"`
}

func (m *ApplyRequest) Reset()                    { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string            { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()               {}
func (*ApplyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApplyRequest) GetM() *math1.Matrix {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *ApplyRequest) GetQ() []*Q {
	if m != nil {
		return m.Q
	}
	return nil
}

type ControlledRequest struct {
	Control []*Q  `protobuf:"bytes,1,rep,name=control" json:"control,omitempty"`
	Target  *Q    `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	K       int64 `protobuf:"varint,3,opt,name=k" json:"k,omitempty"`
}

func (m *ControlledRequest) Reset()                    { *m = ControlledRequest{} }
func (m *ControlledRequest) String() string            { return proto.CompactTextString(m) }
func (*ControlledRequest) ProtoMessage()               {}
func (*ControlledRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ControlledRequest) GetControl() []*Q {
	if m != nil {
		return m.Control
	}
	return nil
}

func (m *ControlledRequest) GetTarget() *Q {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *ControlledRequest) GetK() int64 {
	if m != nil {
		return m.K
	}
	return 0
}

type QResponse struct {
	Q *Q `protobuf:"bytes,1,opt,name=q" json:"q,omitempty"`
}

func (m *QResponse) Reset()                    { *m = QResponse{} }
func (m *QResponse) String() string            { return proto.CompactTextString(m) }
func (*QResponse) ProtoMessage()               {}
func (*QResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QResponse) GetQ() *Q {
	if m != nil {
		return m.Q
	}
	return nil
}

func init() {
	proto.RegisterType((*Q)(nil), "qsim.Q")
	proto.RegisterType((*QRequest)(nil), "qsim.QRequest")
	proto.RegisterType((*ApplyRequest)(nil), "qsim.ApplyRequest")
	proto.RegisterType((*ControlledRequest)(nil), "qsim.ControlledRequest")
	proto.RegisterType((*QResponse)(nil), "qsim.QResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Qsim service

type QsimClient interface {
	H(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error)
	X(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error)
	Y(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error)
	Z(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error)
	S(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error)
	T(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error)
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*QResponse, error)
	ControlledR(ctx context.Context, in *ControlledRequest, opts ...grpc.CallOption) (*QResponse, error)
	ControlledZ(ctx context.Context, in *ControlledRequest, opts ...grpc.CallOption) (*QResponse, error)
	ControlledNOT(ctx context.Context, in *ControlledRequest, opts ...grpc.CallOption) (*QResponse, error)
	QFT(ctx context.Context, in *qubit.Empty, opts ...grpc.CallOption) (*QResponse, error)
	InverseQFT(ctx context.Context, in *qubit.Empty, opts ...grpc.CallOption) (*QResponse, error)
}

type qsimClient struct {
	cc *grpc.ClientConn
}

func NewQsimClient(cc *grpc.ClientConn) QsimClient {
	return &qsimClient{cc}
}

func (c *qsimClient) H(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/H", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) X(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/X", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) Y(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/Y", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) Z(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/Z", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) S(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/S", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) T(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/T", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/Apply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) ControlledR(ctx context.Context, in *ControlledRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/ControlledR", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) ControlledZ(ctx context.Context, in *ControlledRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/ControlledZ", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) ControlledNOT(ctx context.Context, in *ControlledRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/ControlledNOT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) QFT(ctx context.Context, in *qubit.Empty, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/QFT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qsimClient) InverseQFT(ctx context.Context, in *qubit.Empty, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qsim.Qsim/InverseQFT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Qsim service

type QsimServer interface {
	H(context.Context, *QRequest) (*QResponse, error)
	X(context.Context, *QRequest) (*QResponse, error)
	Y(context.Context, *QRequest) (*QResponse, error)
	Z(context.Context, *QRequest) (*QResponse, error)
	S(context.Context, *QRequest) (*QResponse, error)
	T(context.Context, *QRequest) (*QResponse, error)
	Apply(context.Context, *ApplyRequest) (*QResponse, error)
	ControlledR(context.Context, *ControlledRequest) (*QResponse, error)
	ControlledZ(context.Context, *ControlledRequest) (*QResponse, error)
	ControlledNOT(context.Context, *ControlledRequest) (*QResponse, error)
	QFT(context.Context, *qubit.Empty) (*QResponse, error)
	InverseQFT(context.Context, *qubit.Empty) (*QResponse, error)
}

func RegisterQsimServer(s *grpc.Server, srv QsimServer) {
	s.RegisterService(&_Qsim_serviceDesc, srv)
}

func _Qsim_H_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).H(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/H",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).H(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_X_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).X(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/X",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).X(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_Y_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).Y(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/Y",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).Y(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_Z_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).Z(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/Z",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).Z(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_S_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).S(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/S",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).S(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_T_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).T(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/T",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).T(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_ControlledR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).ControlledR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/ControlledR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).ControlledR(ctx, req.(*ControlledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_ControlledZ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).ControlledZ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/ControlledZ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).ControlledZ(ctx, req.(*ControlledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_ControlledNOT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).ControlledNOT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/ControlledNOT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).ControlledNOT(ctx, req.(*ControlledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_QFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(qubit.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).QFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/QFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).QFT(ctx, req.(*qubit.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qsim_InverseQFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(qubit.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QsimServer).InverseQFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qsim.Qsim/InverseQFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QsimServer).InverseQFT(ctx, req.(*qubit.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Qsim_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qsim.Qsim",
	HandlerType: (*QsimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "H",
			Handler:    _Qsim_H_Handler,
		},
		{
			MethodName: "X",
			Handler:    _Qsim_X_Handler,
		},
		{
			MethodName: "Y",
			Handler:    _Qsim_Y_Handler,
		},
		{
			MethodName: "Z",
			Handler:    _Qsim_Z_Handler,
		},
		{
			MethodName: "S",
			Handler:    _Qsim_S_Handler,
		},
		{
			MethodName: "T",
			Handler:    _Qsim_T_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Qsim_Apply_Handler,
		},
		{
			MethodName: "ControlledR",
			Handler:    _Qsim_ControlledR_Handler,
		},
		{
			MethodName: "ControlledZ",
			Handler:    _Qsim_ControlledZ_Handler,
		},
		{
			MethodName: "ControlledNOT",
			Handler:    _Qsim_ControlledNOT_Handler,
		},
		{
			MethodName: "QFT",
			Handler:    _Qsim_QFT_Handler,
		},
		{
			MethodName: "InverseQFT",
			Handler:    _Qsim_InverseQFT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "q.proto",
}

func init() { proto.RegisterFile("q.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcb, 0x4f, 0xc2, 0x40,
	0x10, 0xc6, 0x1d, 0xca, 0x43, 0x07, 0x94, 0xb0, 0x89, 0xb1, 0xa9, 0x07, 0xa1, 0x07, 0xe4, 0x62,
	0x49, 0xd0, 0x8b, 0xf1, 0x04, 0x46, 0xa3, 0x07, 0x1f, 0xad, 0x1c, 0x94, 0x5b, 0xc1, 0x0d, 0x34,
	0xb0, 0xf4, 0xb1, 0x8b, 0x11, 0xff, 0x2a, 0xff, 0x44, 0xd3, 0x5d, 0x8b, 0x28, 0x24, 0x96, 0xcb,
	0x24, 0x9d, 0xf9, 0xcd, 0xf7, 0x6d, 0xf3, 0xed, 0x62, 0x21, 0xb4, 0x82, 0xc8, 0x17, 0x3e, 0xc9,
	0x86, 0xdc, 0x63, 0x46, 0x25, 0x9c, 0xf5, 0x3d, 0xd1, 0x94, 0x55, 0x0d, 0x8c, 0x32, 0x73, 0xc5,
	0xa8, 0x19, 0x17, 0xd5, 0x30, 0x8f, 0x11, 0x6c, 0x62, 0x62, 0x4e, 0x42, 0x3a, 0x54, 0xa1, 0x51,
	0x6c, 0x95, 0x2c, 0xb5, 0x62, 0xc7, 0xd5, 0x51, 0x23, 0xb3, 0x86, 0xdb, 0xb6, 0x43, 0xc3, 0x19,
	0xe5, 0x82, 0xec, 0x23, 0x84, 0x3a, 0x54, 0xb5, 0x46, 0xb1, 0x55, 0xb0, 0x62, 0x2b, 0xcb, 0x76,
	0x20, 0x34, 0xdb, 0x58, 0x6a, 0x07, 0xc1, 0x64, 0x9e, 0x60, 0x06, 0x02, 0x5b, 0x48, 0x4a, 0xcf,
	0x3b, 0x57, 0x44, 0xde, 0xbb, 0x03, 0x4c, 0x49, 0x64, 0x56, 0x24, 0x28, 0x56, 0x2e, 0xfd, 0xa9,
	0x88, 0xfc, 0xc9, 0x84, 0xbe, 0x26, 0x3a, 0x35, 0x2c, 0x0c, 0x54, 0xf3, 0xaf, 0x69, 0xd2, 0x27,
	0x47, 0x98, 0x17, 0x6e, 0x34, 0xa4, 0x42, 0xcf, 0x48, 0xbf, 0x05, 0xf1, 0xdd, 0x26, 0x25, 0x84,
	0xb1, 0xae, 0x55, 0xa1, 0xa1, 0x39, 0x30, 0x36, 0x4d, 0xdc, 0xb1, 0x1d, 0xca, 0x03, 0x7f, 0xca,
	0x69, 0xf2, 0x37, 0xf0, 0xfb, 0x28, 0xad, 0xcf, 0x2c, 0x66, 0x6d, 0xee, 0x31, 0x52, 0x47, 0xb8,
	0x21, 0x7b, 0xc9, 0x44, 0x9d, 0xc9, 0x28, 0x2f, 0xbe, 0x95, 0x8a, 0xb9, 0x15, 0x73, 0xcf, 0x29,
	0xb9, 0x97, 0x94, 0x5c, 0x2f, 0x25, 0xf7, 0x94, 0x92, 0xeb, 0xa6, 0xe1, 0x2c, 0xcc, 0xc9, 0x18,
	0x09, 0x51, 0xb3, 0xe5, 0x4c, 0xd7, 0xf1, 0xe7, 0x58, 0x5c, 0xca, 0x8c, 0x1c, 0x28, 0x62, 0x25,
	0xc6, 0x7f, 0x57, 0x7b, 0x1b, 0xad, 0x5e, 0xe0, 0xee, 0x0f, 0x77, 0xff, 0xd0, 0xdd, 0x68, 0xb9,
	0x8e, 0x9a, 0x7d, 0xdd, 0x25, 0xc9, 0x45, 0xbf, 0x62, 0x81, 0x98, 0xaf, 0xe3, 0x4e, 0x10, 0x6f,
	0xa7, 0x6f, 0x34, 0xe2, 0x34, 0x0d, 0xde, 0x39, 0xc4, 0xca, 0xc0, 0x67, 0xd6, 0xd0, 0x13, 0xa3,
	0x59, 0xbf, 0xc9, 0xdd, 0xd1, 0x19, 0xfd, 0xe8, 0xc8, 0xb7, 0xf8, 0x08, 0xfd, 0xbc, 0x7c, 0x70,
	0xa7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x3e, 0x86, 0xf0, 0xa5, 0x03, 0x00, 0x00,
}
