// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qubit.proto

/*
Package qubit is a generated protocol buffer package.

It is generated from these files:
	qubit.proto

It has these top-level messages:
	Qubit
	Empty
	NumberOfBitResponse
	EpsRequest
	BoolResponse
	DoubleResponse
	QRequest
	QResponse
	Complex128Response
	MatrixRequest
	MatrixResponse
	EqualsRequest
	AmplitudeResponse
	ProbabilityResponse
	MeasureRequest
	BitRequest
	ProbabilityAtResponse
*/
package qubit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import math1 "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Qubit struct {
	Vector *math1.Vector `protobuf:"bytes,1,opt,name=vector" json:"vector,omitempty"`
}

func (m *Qubit) Reset()                    { *m = Qubit{} }
func (m *Qubit) String() string            { return proto.CompactTextString(m) }
func (*Qubit) ProtoMessage()               {}
func (*Qubit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Qubit) GetVector() *math1.Vector {
	if m != nil {
		return m.Vector
	}
	return nil
}

// None is empty request
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NumberOfBitResponse struct {
	Bit int32 `protobuf:"varint,1,opt,name=bit" json:"bit,omitempty"`
}

func (m *NumberOfBitResponse) Reset()                    { *m = NumberOfBitResponse{} }
func (m *NumberOfBitResponse) String() string            { return proto.CompactTextString(m) }
func (*NumberOfBitResponse) ProtoMessage()               {}
func (*NumberOfBitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NumberOfBitResponse) GetBit() int32 {
	if m != nil {
		return m.Bit
	}
	return 0
}

type EpsRequest struct {
	Eps []float64 `protobuf:"fixed64,1,rep,packed,name=eps" json:"eps,omitempty"`
}

func (m *EpsRequest) Reset()                    { *m = EpsRequest{} }
func (m *EpsRequest) String() string            { return proto.CompactTextString(m) }
func (*EpsRequest) ProtoMessage()               {}
func (*EpsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EpsRequest) GetEps() []float64 {
	if m != nil {
		return m.Eps
	}
	return nil
}

type BoolResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *BoolResponse) Reset()                    { *m = BoolResponse{} }
func (m *BoolResponse) String() string            { return proto.CompactTextString(m) }
func (*BoolResponse) ProtoMessage()               {}
func (*BoolResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BoolResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type DoubleResponse struct {
	Data float64 `protobuf:"fixed64,1,opt,name=data" json:"data,omitempty"`
}

func (m *DoubleResponse) Reset()                    { *m = DoubleResponse{} }
func (m *DoubleResponse) String() string            { return proto.CompactTextString(m) }
func (*DoubleResponse) ProtoMessage()               {}
func (*DoubleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DoubleResponse) GetData() float64 {
	if m != nil {
		return m.Data
	}
	return 0
}

type QRequest struct {
	Qubit *Qubit `protobuf:"bytes,1,opt,name=qubit" json:"qubit,omitempty"`
}

func (m *QRequest) Reset()                    { *m = QRequest{} }
func (m *QRequest) String() string            { return proto.CompactTextString(m) }
func (*QRequest) ProtoMessage()               {}
func (*QRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *QRequest) GetQubit() *Qubit {
	if m != nil {
		return m.Qubit
	}
	return nil
}

type QResponse struct {
	Qubit *Qubit `protobuf:"bytes,1,opt,name=qubit" json:"qubit,omitempty"`
}

func (m *QResponse) Reset()                    { *m = QResponse{} }
func (m *QResponse) String() string            { return proto.CompactTextString(m) }
func (*QResponse) ProtoMessage()               {}
func (*QResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *QResponse) GetQubit() *Qubit {
	if m != nil {
		return m.Qubit
	}
	return nil
}

type Complex128Response struct {
	Complex *math1.Complex128 `protobuf:"bytes,1,opt,name=complex" json:"complex,omitempty"`
}

func (m *Complex128Response) Reset()                    { *m = Complex128Response{} }
func (m *Complex128Response) String() string            { return proto.CompactTextString(m) }
func (*Complex128Response) ProtoMessage()               {}
func (*Complex128Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Complex128Response) GetComplex() *math1.Complex128 {
	if m != nil {
		return m.Complex
	}
	return nil
}

type MatrixRequest struct {
	Matrix *math1.Matrix `protobuf:"bytes,1,opt,name=matrix" json:"matrix,omitempty"`
}

func (m *MatrixRequest) Reset()                    { *m = MatrixRequest{} }
func (m *MatrixRequest) String() string            { return proto.CompactTextString(m) }
func (*MatrixRequest) ProtoMessage()               {}
func (*MatrixRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MatrixRequest) GetMatrix() *math1.Matrix {
	if m != nil {
		return m.Matrix
	}
	return nil
}

type MatrixResponse struct {
	Matrix *math1.Matrix `protobuf:"bytes,1,opt,name=matrix" json:"matrix,omitempty"`
}

func (m *MatrixResponse) Reset()                    { *m = MatrixResponse{} }
func (m *MatrixResponse) String() string            { return proto.CompactTextString(m) }
func (*MatrixResponse) ProtoMessage()               {}
func (*MatrixResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MatrixResponse) GetMatrix() *math1.Matrix {
	if m != nil {
		return m.Matrix
	}
	return nil
}

type EqualsRequest struct {
	Qubit *Qubit    `protobuf:"bytes,1,opt,name=qubit" json:"qubit,omitempty"`
	Eps   []float64 `protobuf:"fixed64,2,rep,packed,name=eps" json:"eps,omitempty"`
}

func (m *EqualsRequest) Reset()                    { *m = EqualsRequest{} }
func (m *EqualsRequest) String() string            { return proto.CompactTextString(m) }
func (*EqualsRequest) ProtoMessage()               {}
func (*EqualsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *EqualsRequest) GetQubit() *Qubit {
	if m != nil {
		return m.Qubit
	}
	return nil
}

func (m *EqualsRequest) GetEps() []float64 {
	if m != nil {
		return m.Eps
	}
	return nil
}

type AmplitudeResponse struct {
	Complex []*math1.Complex128 `protobuf:"bytes,1,rep,name=complex" json:"complex,omitempty"`
}

func (m *AmplitudeResponse) Reset()                    { *m = AmplitudeResponse{} }
func (m *AmplitudeResponse) String() string            { return proto.CompactTextString(m) }
func (*AmplitudeResponse) ProtoMessage()               {}
func (*AmplitudeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AmplitudeResponse) GetComplex() []*math1.Complex128 {
	if m != nil {
		return m.Complex
	}
	return nil
}

type ProbabilityResponse struct {
	Data []float64 `protobuf:"fixed64,1,rep,packed,name=data" json:"data,omitempty"`
}

func (m *ProbabilityResponse) Reset()                    { *m = ProbabilityResponse{} }
func (m *ProbabilityResponse) String() string            { return proto.CompactTextString(m) }
func (*ProbabilityResponse) ProtoMessage()               {}
func (*ProbabilityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ProbabilityResponse) GetData() []float64 {
	if m != nil {
		return m.Data
	}
	return nil
}

type MeasureRequest struct {
	Bit []int32 `protobuf:"varint,1,rep,packed,name=bit" json:"bit,omitempty"`
}

func (m *MeasureRequest) Reset()                    { *m = MeasureRequest{} }
func (m *MeasureRequest) String() string            { return proto.CompactTextString(m) }
func (*MeasureRequest) ProtoMessage()               {}
func (*MeasureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MeasureRequest) GetBit() []int32 {
	if m != nil {
		return m.Bit
	}
	return nil
}

type BitRequest struct {
	Bit int32 `protobuf:"varint,1,opt,name=bit" json:"bit,omitempty"`
}

func (m *BitRequest) Reset()                    { *m = BitRequest{} }
func (m *BitRequest) String() string            { return proto.CompactTextString(m) }
func (*BitRequest) ProtoMessage()               {}
func (*BitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *BitRequest) GetBit() int32 {
	if m != nil {
		return m.Bit
	}
	return 0
}

type ProbabilityAtResponse struct {
	I []int32   `protobuf:"varint,1,rep,packed,name=i" json:"i,omitempty"`
	D []float64 `protobuf:"fixed64,2,rep,packed,name=d" json:"d,omitempty"`
}

func (m *ProbabilityAtResponse) Reset()                    { *m = ProbabilityAtResponse{} }
func (m *ProbabilityAtResponse) String() string            { return proto.CompactTextString(m) }
func (*ProbabilityAtResponse) ProtoMessage()               {}
func (*ProbabilityAtResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ProbabilityAtResponse) GetI() []int32 {
	if m != nil {
		return m.I
	}
	return nil
}

func (m *ProbabilityAtResponse) GetD() []float64 {
	if m != nil {
		return m.D
	}
	return nil
}

func init() {
	proto.RegisterType((*Qubit)(nil), "qubit.Qubit")
	proto.RegisterType((*Empty)(nil), "qubit.Empty")
	proto.RegisterType((*NumberOfBitResponse)(nil), "qubit.NumberOfBitResponse")
	proto.RegisterType((*EpsRequest)(nil), "qubit.EpsRequest")
	proto.RegisterType((*BoolResponse)(nil), "qubit.BoolResponse")
	proto.RegisterType((*DoubleResponse)(nil), "qubit.DoubleResponse")
	proto.RegisterType((*QRequest)(nil), "qubit.QRequest")
	proto.RegisterType((*QResponse)(nil), "qubit.QResponse")
	proto.RegisterType((*Complex128Response)(nil), "qubit.Complex128Response")
	proto.RegisterType((*MatrixRequest)(nil), "qubit.MatrixRequest")
	proto.RegisterType((*MatrixResponse)(nil), "qubit.MatrixResponse")
	proto.RegisterType((*EqualsRequest)(nil), "qubit.EqualsRequest")
	proto.RegisterType((*AmplitudeResponse)(nil), "qubit.AmplitudeResponse")
	proto.RegisterType((*ProbabilityResponse)(nil), "qubit.ProbabilityResponse")
	proto.RegisterType((*MeasureRequest)(nil), "qubit.MeasureRequest")
	proto.RegisterType((*BitRequest)(nil), "qubit.BitRequest")
	proto.RegisterType((*ProbabilityAtResponse)(nil), "qubit.ProbabilityAtResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for QQubit service

type QQubitClient interface {
	NumberOfBit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NumberOfBitResponse, error)
	IsZero(ctx context.Context, in *EpsRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	IsOne(ctx context.Context, in *EpsRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	InnerProduct(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*Complex128Response, error)
	OuterProduct(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*MatrixResponse, error)
	Fidelity(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*DoubleResponse, error)
	TraceDistance(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*DoubleResponse, error)
	Equals(ctx context.Context, in *EqualsRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	TensorProduct(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error)
	Apply(ctx context.Context, in *MatrixRequest, opts ...grpc.CallOption) (*QResponse, error)
	Normalize(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QResponse, error)
	Amplitude(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AmplitudeResponse, error)
	Probability(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProbabilityResponse, error)
	Measure(ctx context.Context, in *MeasureRequest, opts ...grpc.CallOption) (*QResponse, error)
	ProbabilityZeroAt(ctx context.Context, in *BitRequest, opts ...grpc.CallOption) (*ProbabilityAtResponse, error)
	ProbabilityOneAt(ctx context.Context, in *BitRequest, opts ...grpc.CallOption) (*ProbabilityAtResponse, error)
	MeasureAt(ctx context.Context, in *BitRequest, opts ...grpc.CallOption) (*QResponse, error)
}

type qQubitClient struct {
	cc *grpc.ClientConn
}

func NewQQubitClient(cc *grpc.ClientConn) QQubitClient {
	return &qQubitClient{cc}
}

func (c *qQubitClient) NumberOfBit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NumberOfBitResponse, error) {
	out := new(NumberOfBitResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/NumberOfBit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) IsZero(ctx context.Context, in *EpsRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/IsZero", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) IsOne(ctx context.Context, in *EpsRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/IsOne", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) InnerProduct(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*Complex128Response, error) {
	out := new(Complex128Response)
	err := grpc.Invoke(ctx, "/qubit.QQubit/InnerProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) OuterProduct(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*MatrixResponse, error) {
	out := new(MatrixResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/OuterProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) Fidelity(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*DoubleResponse, error) {
	out := new(DoubleResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/Fidelity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) TraceDistance(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*DoubleResponse, error) {
	out := new(DoubleResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/TraceDistance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) Equals(ctx context.Context, in *EqualsRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/Equals", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) TensorProduct(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/TensorProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) Apply(ctx context.Context, in *MatrixRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/Apply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) Normalize(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/Normalize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) Amplitude(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AmplitudeResponse, error) {
	out := new(AmplitudeResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/Amplitude", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) Probability(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProbabilityResponse, error) {
	out := new(ProbabilityResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/Probability", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) Measure(ctx context.Context, in *MeasureRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/Measure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) ProbabilityZeroAt(ctx context.Context, in *BitRequest, opts ...grpc.CallOption) (*ProbabilityAtResponse, error) {
	out := new(ProbabilityAtResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/ProbabilityZeroAt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) ProbabilityOneAt(ctx context.Context, in *BitRequest, opts ...grpc.CallOption) (*ProbabilityAtResponse, error) {
	out := new(ProbabilityAtResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/ProbabilityOneAt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qQubitClient) MeasureAt(ctx context.Context, in *BitRequest, opts ...grpc.CallOption) (*QResponse, error) {
	out := new(QResponse)
	err := grpc.Invoke(ctx, "/qubit.QQubit/MeasureAt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QQubit service

type QQubitServer interface {
	NumberOfBit(context.Context, *Empty) (*NumberOfBitResponse, error)
	IsZero(context.Context, *EpsRequest) (*BoolResponse, error)
	IsOne(context.Context, *EpsRequest) (*BoolResponse, error)
	InnerProduct(context.Context, *QRequest) (*Complex128Response, error)
	OuterProduct(context.Context, *QRequest) (*MatrixResponse, error)
	Fidelity(context.Context, *QRequest) (*DoubleResponse, error)
	TraceDistance(context.Context, *QRequest) (*DoubleResponse, error)
	Equals(context.Context, *EqualsRequest) (*BoolResponse, error)
	TensorProduct(context.Context, *QRequest) (*QResponse, error)
	Apply(context.Context, *MatrixRequest) (*QResponse, error)
	Normalize(context.Context, *Empty) (*QResponse, error)
	Amplitude(context.Context, *Empty) (*AmplitudeResponse, error)
	Probability(context.Context, *Empty) (*ProbabilityResponse, error)
	Measure(context.Context, *MeasureRequest) (*QResponse, error)
	ProbabilityZeroAt(context.Context, *BitRequest) (*ProbabilityAtResponse, error)
	ProbabilityOneAt(context.Context, *BitRequest) (*ProbabilityAtResponse, error)
	MeasureAt(context.Context, *BitRequest) (*QResponse, error)
}

func RegisterQQubitServer(s *grpc.Server, srv QQubitServer) {
	s.RegisterService(&_QQubit_serviceDesc, srv)
}

func _QQubit_NumberOfBit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).NumberOfBit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/NumberOfBit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).NumberOfBit(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_IsZero_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).IsZero(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/IsZero",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).IsZero(ctx, req.(*EpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_IsOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).IsOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/IsOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).IsOne(ctx, req.(*EpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_InnerProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).InnerProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/InnerProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).InnerProduct(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_OuterProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).OuterProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/OuterProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).OuterProduct(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_Fidelity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).Fidelity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/Fidelity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).Fidelity(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_TraceDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).TraceDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/TraceDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).TraceDistance(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_Equals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EqualsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).Equals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/Equals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).Equals(ctx, req.(*EqualsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_TensorProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).TensorProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/TensorProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).TensorProduct(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).Apply(ctx, req.(*MatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_Normalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).Normalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/Normalize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).Normalize(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_Amplitude_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).Amplitude(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/Amplitude",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).Amplitude(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_Probability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).Probability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/Probability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).Probability(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_Measure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).Measure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/Measure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).Measure(ctx, req.(*MeasureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_ProbabilityZeroAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).ProbabilityZeroAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/ProbabilityZeroAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).ProbabilityZeroAt(ctx, req.(*BitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_ProbabilityOneAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).ProbabilityOneAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/ProbabilityOneAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).ProbabilityOneAt(ctx, req.(*BitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QQubit_MeasureAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QQubitServer).MeasureAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qubit.QQubit/MeasureAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QQubitServer).MeasureAt(ctx, req.(*BitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QQubit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qubit.QQubit",
	HandlerType: (*QQubitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NumberOfBit",
			Handler:    _QQubit_NumberOfBit_Handler,
		},
		{
			MethodName: "IsZero",
			Handler:    _QQubit_IsZero_Handler,
		},
		{
			MethodName: "IsOne",
			Handler:    _QQubit_IsOne_Handler,
		},
		{
			MethodName: "InnerProduct",
			Handler:    _QQubit_InnerProduct_Handler,
		},
		{
			MethodName: "OuterProduct",
			Handler:    _QQubit_OuterProduct_Handler,
		},
		{
			MethodName: "Fidelity",
			Handler:    _QQubit_Fidelity_Handler,
		},
		{
			MethodName: "TraceDistance",
			Handler:    _QQubit_TraceDistance_Handler,
		},
		{
			MethodName: "Equals",
			Handler:    _QQubit_Equals_Handler,
		},
		{
			MethodName: "TensorProduct",
			Handler:    _QQubit_TensorProduct_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _QQubit_Apply_Handler,
		},
		{
			MethodName: "Normalize",
			Handler:    _QQubit_Normalize_Handler,
		},
		{
			MethodName: "Amplitude",
			Handler:    _QQubit_Amplitude_Handler,
		},
		{
			MethodName: "Probability",
			Handler:    _QQubit_Probability_Handler,
		},
		{
			MethodName: "Measure",
			Handler:    _QQubit_Measure_Handler,
		},
		{
			MethodName: "ProbabilityZeroAt",
			Handler:    _QQubit_ProbabilityZeroAt_Handler,
		},
		{
			MethodName: "ProbabilityOneAt",
			Handler:    _QQubit_ProbabilityOneAt_Handler,
		},
		{
			MethodName: "MeasureAt",
			Handler:    _QQubit_MeasureAt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qubit.proto",
}

func init() { proto.RegisterFile("qubit.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x6f, 0x4f, 0xdb, 0x3e,
	0x10, 0x6e, 0xe8, 0xaf, 0x2d, 0xbd, 0xfe, 0xa1, 0x35, 0x3f, 0x24, 0x56, 0x21, 0x84, 0x2c, 0xa4,
	0xb1, 0x49, 0x14, 0x51, 0x60, 0x02, 0x69, 0xd2, 0xd6, 0x8e, 0x22, 0xf1, 0x02, 0x4a, 0x23, 0xb4,
	0x17, 0x7b, 0x97, 0xb4, 0xde, 0xb0, 0x48, 0xe2, 0x10, 0x3b, 0x13, 0xf0, 0x1d, 0xf7, 0x9d, 0xa6,
	0x38, 0x8e, 0xeb, 0x42, 0x8a, 0x60, 0x6f, 0x2a, 0xfb, 0xee, 0x9e, 0x3b, 0xdf, 0xdd, 0xf3, 0x34,
	0x50, 0xbb, 0x8b, 0x5d, 0x2a, 0xba, 0x61, 0xc4, 0x04, 0x43, 0x25, 0x79, 0xe9, 0xac, 0xf8, 0x8e,
	0xb8, 0xd9, 0x4b, 0x7e, 0x52, 0x3b, 0xde, 0x85, 0xd2, 0x38, 0xf1, 0xa0, 0x6d, 0x28, 0xff, 0x26,
	0x13, 0xc1, 0xa2, 0x75, 0x6b, 0xcb, 0xda, 0xa9, 0xf5, 0xea, 0x5d, 0x19, 0xf5, 0x5d, 0xda, 0x6c,
	0xe5, 0xc3, 0x15, 0x28, 0x0d, 0xfd, 0x50, 0x3c, 0xe0, 0xf7, 0xb0, 0x7a, 0x19, 0xfb, 0x2e, 0x89,
	0x46, 0x3f, 0x07, 0x54, 0xd8, 0x84, 0x87, 0x2c, 0xe0, 0x04, 0xb5, 0xa0, 0xe8, 0x52, 0x21, 0x53,
	0x94, 0xec, 0xe4, 0x88, 0x37, 0x01, 0x86, 0x21, 0xb7, 0xc9, 0x5d, 0x4c, 0xb8, 0x48, 0xfc, 0x24,
	0xe4, 0xeb, 0xd6, 0x56, 0x71, 0xc7, 0xb2, 0x93, 0x23, 0xde, 0x84, 0xfa, 0x80, 0x31, 0x4f, 0x67,
	0x68, 0xc2, 0x12, 0xbb, 0x95, 0x09, 0x96, 0xed, 0x25, 0x76, 0x8b, 0xb7, 0xa1, 0x79, 0xca, 0x62,
	0xd7, 0x23, 0x3a, 0x02, 0xc1, 0x7f, 0x53, 0x47, 0x38, 0x32, 0xc6, 0xb2, 0xe5, 0x19, 0x77, 0x61,
	0x79, 0x9c, 0xd5, 0xc0, 0x90, 0x36, 0xab, 0x1b, 0x49, 0xe7, 0x20, 0xdb, 0xb4, 0x53, 0x17, 0xde,
	0x83, 0xea, 0x58, 0x27, 0x7c, 0x0d, 0xe0, 0x2b, 0xa0, 0x6f, 0xcc, 0x0f, 0x3d, 0x72, 0xbf, 0xdf,
	0x3b, 0xd6, 0xc8, 0x8f, 0x50, 0x99, 0xa4, 0x56, 0x85, 0x6d, 0xa5, 0x53, 0x33, 0x42, 0xb3, 0x00,
	0x7c, 0x04, 0x8d, 0x0b, 0x47, 0x44, 0xf4, 0x3e, 0x7b, 0xe7, 0x36, 0x94, 0x7d, 0x69, 0x98, 0x9f,
	0xb8, 0x0a, 0x52, 0x3e, 0xfc, 0x09, 0x9a, 0x19, 0x4c, 0x15, 0x7d, 0x1d, 0x6e, 0x08, 0x8d, 0xe1,
	0x5d, 0xec, 0x78, 0xfc, 0x0d, 0x63, 0xc9, 0xd6, 0xb3, 0x34, 0x5b, 0xcf, 0x17, 0x68, 0xf7, 0xfd,
	0xd0, 0xa3, 0x22, 0x9e, 0x92, 0xfc, 0xb6, 0x8b, 0x2f, 0xb7, 0xfd, 0x01, 0x56, 0xaf, 0x22, 0xe6,
	0x3a, 0x2e, 0xf5, 0xa8, 0x78, 0xc8, 0x59, 0x62, 0x51, 0x2f, 0x11, 0x43, 0xf3, 0x82, 0x38, 0x3c,
	0x8e, 0x88, 0x41, 0x97, 0xf4, 0xc5, 0x45, 0x83, 0x4e, 0x92, 0x6f, 0x4f, 0xfc, 0x9a, 0x6e, 0x07,
	0xb0, 0x66, 0x94, 0xeb, 0xcf, 0x98, 0x59, 0x07, 0x8b, 0xaa, 0x44, 0x16, 0x4d, 0x6e, 0x53, 0xd5,
	0xa6, 0x35, 0xed, 0xfd, 0xa9, 0x40, 0x79, 0x9c, 0xca, 0xe0, 0x04, 0x6a, 0x06, 0xaf, 0x51, 0x36,
	0x25, 0x49, 0xfa, 0x4e, 0x47, 0xdd, 0x72, 0x98, 0x8f, 0x0b, 0xa8, 0x07, 0xe5, 0x73, 0xfe, 0x83,
	0x44, 0x0c, 0xb5, 0x33, 0x94, 0x26, 0x7e, 0x67, 0x55, 0x99, 0x4c, 0xae, 0xe3, 0x02, 0xda, 0x87,
	0xd2, 0x39, 0x1f, 0x05, 0xe4, 0x0d, 0x90, 0xcf, 0x50, 0x3f, 0x0f, 0x02, 0x12, 0x5d, 0x45, 0x6c,
	0x1a, 0x4f, 0x04, 0x5a, 0xc9, 0x16, 0x99, 0xe1, 0xde, 0x29, 0xc3, 0x73, 0xbe, 0xe2, 0x02, 0x3a,
	0x86, 0xfa, 0x28, 0x16, 0x2f, 0xa0, 0xd7, 0x94, 0x61, 0x9e, 0x74, 0xb8, 0x80, 0x0e, 0x61, 0xf9,
	0x8c, 0x4e, 0x49, 0x32, 0xd6, 0xc5, 0xa8, 0x79, 0xa9, 0xe2, 0x02, 0x3a, 0x81, 0xc6, 0x75, 0xe4,
	0x4c, 0xc8, 0x29, 0xe5, 0xc2, 0x09, 0x26, 0xe4, 0x0d, 0xd0, 0x23, 0x28, 0xa7, 0x0c, 0x46, 0xff,
	0x67, 0xc3, 0x31, 0x09, 0xbd, 0x68, 0x3e, 0x87, 0xd0, 0xb8, 0x26, 0x01, 0x67, 0x8b, 0x5b, 0x6c,
	0xcd, 0x0c, 0xe6, 0x22, 0xfa, 0x61, 0xe8, 0x3d, 0xe8, 0x5a, 0x73, 0x5a, 0xcd, 0x85, 0xec, 0x42,
	0xf5, 0x92, 0x45, 0xbe, 0xe3, 0xd1, 0x47, 0xf2, 0x84, 0x28, 0x79, 0xe1, 0x47, 0x50, 0xd5, 0x4a,
	0x7a, 0x12, 0xbe, 0xae, 0x6e, 0xcf, 0x94, 0x26, 0x07, 0x58, 0x33, 0x08, 0xbd, 0x80, 0x90, 0x39,
	0x0a, 0x93, 0x93, 0xa8, 0x28, 0x3d, 0x21, 0xbd, 0xd5, 0x39, 0x7d, 0xe5, 0xbe, 0xf3, 0x0c, 0xda,
	0x46, 0xba, 0x84, 0xcf, 0x7d, 0xa1, 0xe9, 0x39, 0xd3, 0x5e, 0x67, 0xe3, 0x79, 0xed, 0xbe, 0x29,
	0x87, 0x21, 0xb4, 0x0c, 0xd7, 0x28, 0x20, 0xff, 0x96, 0xa6, 0x07, 0x55, 0xf5, 0xe8, 0x7c, 0x7c,
	0x4e, 0x0b, 0x83, 0x0d, 0x68, 0x4f, 0x98, 0xdf, 0xfd, 0x45, 0xc5, 0x4d, 0xec, 0xee, 0x71, 0xe7,
	0xe6, 0x90, 0x3c, 0x0e, 0xd2, 0xbf, 0xb8, 0x2b, 0xcb, 0x2d, 0xcb, 0x2f, 0xdf, 0xc1, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x7d, 0x99, 0xfd, 0x5a, 0x20, 0x07, 0x00, 0x00,
}
